load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_specs2_junit_test")

#TODO
#scala_library(
#    name = "noSrcsWithResources",
#    resource_strip_prefix = "test/src/main/scala/scalarules/test/resources/strip",
#    resources = ["nosrc_jar_resource.txt"],
#)
#
#scala_specs2_junit_test(
#    name = "resouceStripPrefixTest",
#    size = "small",
#    srcs = ["ResourceStripPrefixTest.scala"],
#    suffixes = ["Test"],
#    deps = [":noSrcsWithResources"],
#)
